Add code linting to CI workflow
etesync/etesync-dav pull request #223
Opened 2021-06-13 14:49 UTC by sergeyklay

- Add code linting to CI workflow
- Fix code style in `mac_helpers`
- Add changes info to package description
- Use the same linux distro on every CI workflow

/cc @tasn

2021-06-13 19:12 UTC, tasn requested changes

2021-06-13 19:12 UTC, tasn commented on .flake8
> +per-file-ignores =
I'd much rather have it in the file itself than the .flake8 config.

2021-06-13 19:12 UTC, tasn commented on .github/workflows/lint.yml
> +    runs-on: ubuntu-latest
The reason why we are using ubuntu-18.04 for everything, is that we need it in order to generate binaries that work across Linux versions. So we use it everywhere for consistency.
```suggestion
    runs-on: ubuntu-18.04
```

2021-06-13 19:12 UTC, tasn commented on .github/workflows/manual.yml
> +        os: [ubuntu-latest, windows-latest, macos-latest]
It should be 18.04.
```suggestion
        os: [ubuntu-18.04, windows-latest, macos-latest]
```

2021-06-13 20:08 UTC, sergeyklay commented
@tasn Could you please take a look :)

2021-06-14 07:34 UTC, tasn reviewed
Sorry for being a bit annoying, but this change is 40% doing what it says, and the rest is adding changelog information and other unrelated stuff. Could you please split to two PRs?

2021-06-14 08:43 UTC, sergeyklay commented
Yes, of course. I'll do today a bit later

2021-06-14 09:02 UTC, tasn commented
Thanks! Sorry about that, just trying to keep things organised, both for myself and other contributors! \o/

2021-06-14 13:19 UTC, merged

2021-06-14 13:19 UTC, tasn commented
Much better, thanks!

2021-06-14 13:21 UTC, sergeyklay commented
You're welcome :)